name: CI

on:
  push:
    branches: [ master ]
    paths: [ '**.py', '.github/workflows/ci.yml' ]
  pull_request:
    branches: [ master ]
    paths: [ '**.py', '.github/workflows/ci.yml' ]
  workflow_dispatch:  # allow manual triggering
  schedule:
    - cron: '0 12 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "pip"

      - name: Install the package
        run: |
          set -xe
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[data]
          python -m pip install jupytext pytest

      - name: Test (pytest)
        run: pytest -v tests

      - name: Run the docs examples
        run: |
          set -xe
          cd docs/examples
          for f in *.md; do
            jupytext --to py $f
            python ${f%.md}.py
          done
